spring:
  mail:
    host: smtp.gmail.com
    username: codejava.net@gmail.com   
    password: your_email_password
    port: 5055
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
